kind: PersistentVolume
apiVersion: v1
metadata:
  labels:
    type: local
    app.kubernetes.io/name: cloud-native-pv
  name: cloud-native-pv
spec:
  capacity:
   storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cloud-native-store
  local:
    path: /mnt/postgres
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kube-node3
          - kube-master
---
kind: PersistentVolume
apiVersion: v1
metadata:
  labels:
    type: local
    app.kubernetes.io/name: cloud-native-pv2
  name: cloud-native-pv2
spec:
  capacity:
   storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cloud-native-store
  local:
    path: /mnt/postgres
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kube-node2

