apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:15.2
  logLevel: debug
  postgresql:
    parameters:
      wal_sender_timeout: "10s"
      wal_receiver_timeout: "10s"
      wal_keep_size: "256MB"

  resources:
    requests:
      memory: "1Gi"
      cpu: "1"
    limits:
      memory: "1Gi"
      cpu: "1"

  storage:
    size: 1Gi
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: cloud-native-store
      volumeMode: Filesystem
  monitoring:
    enablePodMonitor: true
