apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: postgres-test
  labels:
    app: postgres-test
type: Opaque
data:
    postgres-root-username: cm9vdA==
    postgres-root-password: bXlwYXNzd29yZA==
