kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pgbench-save
  namespace: default
spec:
  storageClassName: storage-pgbench
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
