apiVersion: v1
kind: ConfigMap
metadata:
  name: pgpool-config
  labels:
    name: pgpool-config
data:
  pgpool.conf: |-
    listen_addresses = '*'
    port = 9999
    socket_dir = '/var/run/pgpool'
    pcp_listen_addresses = '*'
    pcp_port = 9898
    pcp_socket_dir = '/var/run/pgpool'
    backend_hostname0 = 'cluster-example-rw'
    backend_port0 = 5432
    backend_weight0 = 1
    backend_flag0 = 'ALWAYS_PRIMARY|DISALLOW_TO_FAILOVER'
    backend_hostname1 = 'cluster-example-r'
    backend_port1 = 5432
    backend_weight1 = 10
    backend_flag1 = 'DISALLOW_TO_FAILOVER'
    sr_check_period = 0
    health_check_period = 0
    backend_clustering_mode = 'streaming_replication'
    num_init_children = 900
    max_pool = 1
    child_life_time = 30
    child_max_connections = 0
    connection_life_time = 30
    client_idle_limit = 60
    connection_cache = on
    load_balance_mode = on
    statement_level_load_balance = on
    ssl = off
    enable_pool_hba = off
    allow_clear_text_frontend_auth = on
    failover_on_backend_error = off
    log_min_messages = warning
    memory_cache_enabled = on
    memqcache_method = shmem
    memqcache_expire = 0
    emqcache_total_size = 512MB
  # If pool_hba.conf isn't configured, Pgpool-II will automatically generate it.
  # Note that to use pool_hba.conf you must set enable_pool_hba = on.
  #  pool_hba.conf: |-
  #    host    all         all                   trust

